version: '3.8'

services:
  my-service:
    build: .
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account-key.json
    volumes:
      - ./df-bq-crypto-sa.json:/app/service-account-key.json
