[tool.poetry]
name = "bq-py-crypto"
version = "0.1.0"
description = ""
authors = ["Hazperera <heperera826@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^1.3.3" 

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
