[tool.poetry]
name = "src"
version = "0.1.0"
description = ""
authors = ["Hazperera <heperera826@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
boto3 = "^1.34.41"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
